import { Product } from '../core/product';
import { Size } from '../core/size';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Cosmic Flow',
    imageUrls: ['../assets/portfolio/Cosmic Flow.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 2,
    name: 'Fence in Black & White',
    imageUrls: ['../assets/portfolio/Fence in Black & White.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 3,
    name: 'Food Truck #01',
    imageUrls: ['../assets/portfolio/Food Truck #01.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 4,
    name: 'Four Water Falls Trail in Black & White #01',
    imageUrls: ['../assets/currentExhibition/Four Water Falls Trail in Black & White #01.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 5,
    name: 'Four Water Falls Trail in Black & White #27',
    imageUrls: ['../assets/currentExhibition/Four Water Falls Trail in Black & White #27.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 6,
    name: 'Grand Canyon in Black & White #01',
    imageUrls: ['../assets/currentExhibition/Grand Canyon in Black & White #01.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  }, 
  {
    id: 7,
    name: 'Grand Canyon in Black & White #05',
    imageUrls: ['../assets/currentExhibition/Grand Canyon in Black & White #05.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  }, {
    id: 8,
    name: 'Grand Canyon in Black & White #21',
    imageUrls: ['../assets/currentExhibition/Grand Canyon in Black & White #21.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 9,
    name: 'Grand Canyon in Black & White #24',
    imageUrls: ['../assets/currentExhibition/Grand Canyon in Black & White #24.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 10,
    name: 'Rainy Day',
    imageUrls: ['../assets/currentExhibition/Rainy Day.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 11,
    name: 'Splash Line',
    imageUrls: ['../assets/currentExhibition/Splash Line.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 12,
    name: 'Stereotypes',
    imageUrls: ['../assets/currentExhibition/Stereotypes.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 13,
    name: 'Universal Edge #01',
    imageUrls: ['../assets/currentExhibition/Universal Edge #01.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 14,
    name: 'Universal Edge #02',
    imageUrls: ['../assets/currentExhibition/Universal Edge #02.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 15,
    name: 'Vortex',
    imageUrls: ['../assets/currentExhibition/Vortex.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 16,
    name: 'Whip & Rose #01',
    imageUrls: ['../assets/currentExhibition/Whip & Rose #01.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 17,
    name: 'Whip & Rose 04',
    imageUrls: ['../assets/currentExhibition/Whip & Rose 04.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 18,
    name: 'Winters Grace in Black & White #05',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #05.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 19,
    name: 'Winters Grace in Black & White #06',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #06.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 20,
    name: 'Winters Grace in Black & White #08',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #08.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 21,
    name: 'Winters Grace in Black & White #09',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #09.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },
  {
    id: 22,
    name: 'Winters Grace in Black & White #10',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #10.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },  
  {
    id: 23,
    name: 'Winters Grace in Black & White #11',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #11.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },  
  {
    id: 24,
    name: 'Winters Grace in Black & White #12',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #12.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },  
  {
    id: 25,
    name: 'Winters Grace in Black & White #15',
    imageUrls: ['../assets/currentExhibition/Winters Grace in Black & White #15.jpg'],
    price: [4500, 130, 160, 240],
    sizes: [Size.ORIGINAL, Size.SMALL, Size.MEDIUM, Size.LARGE],
  },    
];